### ISSUE TITLE
Custom GlobalChat Format

### ISSUE THREAD

**Issue by pinoylifecraft** [NovaFox161/PerWorldChatPlus#1]
Hello @NovaFox161 aka shades161 when a Player does /globalchat the format would " **<globalchatformat> [worldname] playername** " but i set this in my config     **Global: '%global%[%world%][%player%] : %message%'** -   Prefix: '&f&l[ &4&l! &f&l]' is the globalprefix

**Comment by NovaFox161** [comment]
This bug will be patched in the next commit. Thank you for bringing it to our attention!!

**Comment by NovaFox161** [comment]
Fixed in commit [#66a6ea1](https://github.com/NovaFox161/PerWorldChatPlus/commit/66a6ea188780719732dcdc6d51f3f8dfc5706a65)
