### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by HellaMixel** [NovaFox161/PerWorldChatPlus#3]
30.08 18:12:32 [Server] WARN [Fatal Error] :57:86: The reference to entity "render" must end with the ';' delimiter.
30.08 18:12:32 [Server] WARN [PerWorldChatPlus] Update URL is invalid! Report this to Shades161 on her Dev Bukkit Page!

**Comment by NovaFox161** [comment]
Patched in upcoming version; commit: https://github.com/NovaFox161/PerWorldChatPlus/commit/d09a8898aceb9e96561f1fb760a461cc185b8e29
