### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TimtimWinslow** [NovaFox161/PerWorldChatPlus#7]
im gettings this error 

[19:41:37 WARN]: [PerWorldChatPlus] Update URL is invalid! Report this to Shades161 on her Dev Bukkit Page!

**Comment by NovaFox161** [comment]
Its just a warning, not an error. 

Plugin works* just fine without checking for updates automatically

*Plugin hasn't been updated in years. So there is no tested support for modern servers
